#!/usr/bin/env python
# -*- coding: utf-8 -*-
import os, sys
sys.path.insert(0, os.path.join((os.path.dirname(os.path.realpath(__file__))), "src"))

from genpac import main

if __name__ == '__main__':
     main() 