name: build-dev
on:
  push:
    # branches:
    #   - dev
env:
  platform: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
defaults:
  run:
    shell: bash
    working-directory: ./
jobs:
  # tests:
  #   runs-on: ubuntu-latest
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_USER }}
            password: ${{ secrets.DOCKER_TOKEN }}
      - uses: actions/checkout@v4
        with:
          ref: dev
      - run: |
          docker buildx build --push --platform "${{ env.platform }}" -t ${{ secrets.DOCKER_USER }}/genpac:dev .
