name: cook
on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "0 */12 * * *"

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Branch dev
        uses: actions/checkout@v4
        with:
          ref: dev
          path: dev
      - name: Checkout Branch cooked
        uses: actions/checkout@v4
        with:
          ref: cooked
          path: cooked
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: |
          pip install ./dev/ && \
          DEST=./cooked genpac --config=./dev/example/config.ini
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          repository: ./cooked
          commit_message: Automated Change
          push_options: '--force'
